-- ==========================================================
-- FASE 1 (Complemento): Proposta personalizada sem kit base
-- Objetivo: permitir preco separado + markup + desconto
-- sem alterar o fluxo de proposta promocional.
--
-- IMPORTANTE:
-- 1) Execute primeiro em staging.
-- 2) Este script NAO altera as colunas usadas hoje no modo promocional.
-- 3) A persistencia dual ainda pode ser feita depois (RPC/front).
-- ==========================================================

-- -----------------------------
-- AUDITORIA ANTES
-- -----------------------------
-- select column_name, data_type, is_nullable, column_default
-- from information_schema.columns
-- where table_schema = 'public' and table_name = 'propostas'
-- order by ordinal_position;

BEGIN;

-- -----------------------------
-- 1) Colunas de precificacao personalizada
-- -----------------------------
ALTER TABLE public.propostas
  ADD COLUMN IF NOT EXISTS custom_system_power_kwp numeric(10,2),
  ADD COLUMN IF NOT EXISTS custom_equipment_price numeric(12,2),
  ADD COLUMN IF NOT EXISTS custom_service_price numeric(12,2),
  ADD COLUMN IF NOT EXISTS custom_subtotal_price numeric(12,2),
  ADD COLUMN IF NOT EXISTS custom_markup_percent numeric(6,2),
  ADD COLUMN IF NOT EXISTS custom_markup_value numeric(12,2),
  ADD COLUMN IF NOT EXISTS custom_price_before_discount numeric(12,2),
  ADD COLUMN IF NOT EXISTS custom_discount_type text,
  ADD COLUMN IF NOT EXISTS custom_discount_value numeric(12,2),
  ADD COLUMN IF NOT EXISTS custom_total_price numeric(12,2),
  ADD COLUMN IF NOT EXISTS custom_payment_note text,
  ADD COLUMN IF NOT EXISTS custom_commercial_note text;

COMMENT ON COLUMN public.propostas.custom_system_power_kwp IS 'Potencia total do sistema no modo personalizada (kWp).';
COMMENT ON COLUMN public.propostas.custom_equipment_price IS 'Preco de equipamentos informado no modo personalizada.';
COMMENT ON COLUMN public.propostas.custom_service_price IS 'Preco de servicos/instalacao informado no modo personalizada.';
COMMENT ON COLUMN public.propostas.custom_subtotal_price IS 'Subtotal = equipamentos + servicos.';
COMMENT ON COLUMN public.propostas.custom_markup_percent IS 'Markup percentual aplicado sobre subtotal.';
COMMENT ON COLUMN public.propostas.custom_markup_value IS 'Valor monetario de markup aplicado.';
COMMENT ON COLUMN public.propostas.custom_price_before_discount IS 'Preco apos markup e antes de desconto.';
COMMENT ON COLUMN public.propostas.custom_discount_type IS 'Tipo de desconto: value ou percent.';
COMMENT ON COLUMN public.propostas.custom_discount_value IS 'Valor de desconto aplicado.';
COMMENT ON COLUMN public.propostas.custom_total_price IS 'Total final da proposta personalizada.';
COMMENT ON COLUMN public.propostas.custom_payment_note IS 'Condicao de pagamento da proposta personalizada.';
COMMENT ON COLUMN public.propostas.custom_commercial_note IS 'Observacao comercial da proposta personalizada.';

-- -----------------------------
-- 2) Regras basicas de integridade (nao invasivas)
-- -----------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chk_propostas_custom_discount_type'
      AND conrelid = 'public.propostas'::regclass
  ) THEN
    ALTER TABLE public.propostas
      ADD CONSTRAINT chk_propostas_custom_discount_type
      CHECK (
        custom_discount_type IS NULL
        OR custom_discount_type IN ('value', 'percent')
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chk_propostas_custom_values_non_negative'
      AND conrelid = 'public.propostas'::regclass
  ) THEN
    ALTER TABLE public.propostas
      ADD CONSTRAINT chk_propostas_custom_values_non_negative
      CHECK (
        coalesce(custom_system_power_kwp, 0) >= 0
        AND coalesce(custom_equipment_price, 0) >= 0
        AND coalesce(custom_service_price, 0) >= 0
        AND coalesce(custom_subtotal_price, 0) >= 0
        AND coalesce(custom_markup_percent, 0) >= 0
        AND coalesce(custom_markup_value, 0) >= 0
        AND coalesce(custom_price_before_discount, 0) >= 0
        AND coalesce(custom_discount_value, 0) >= 0
        AND coalesce(custom_total_price, 0) >= 0
      );
  END IF;
END $$;

COMMIT;

-- -----------------------------
-- 3) Indices uteis para historico/listagem
-- -----------------------------
CREATE INDEX IF NOT EXISTS idx_propostas_mode_created_at
  ON public.propostas (proposal_mode, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_propostas_custom_total
  ON public.propostas (custom_total_price)
  WHERE proposal_mode = 'PERSONALIZADA';

-- -----------------------------
-- 4) Seed opcional de financiadoras (futuro)
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.financiadoras (
  id bigint generated by default as identity primary key,
  nome text not null,
  url text not null,
  taxa_texto text,
  prazo_texto text,
  cor_css text,
  icone_texto text,
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_financiadoras_nome
  ON public.financiadoras (nome);

INSERT INTO public.financiadoras (nome, url, taxa_texto, prazo_texto, cor_css, icone_texto, ordem, ativo)
VALUES
  ('Solfacil',  'https://app.solfacil.com.br',                                'A partir de 0,79% a.m.', 'Ate 84 meses', 'from-orange-600 to-orange-500',  'SF', 10, true),
  ('BV',        'https://www.bv.com.br/para-voce/credito/financiamento-solar', 'A partir de 0,89% a.m.', 'Ate 60 meses', 'from-blue-700 to-blue-600',      'BV', 20, true),
  ('Santander', 'https://www.santander.com.br/negocios/credito-garantido',      'Consulte condicoes',      'Ate 60 meses', 'from-red-700 to-red-600',        'SA', 30, true),
  ('Sicoob',    'https://www.sicoob.com.br/simuladores',                         'Taxas cooperadas',        'Ate 84 meses', 'from-green-700 to-green-600',    'SC', 40, true),
  ('Sicredi',   'https://www.sicredi.com.br/site/para-voce/credito/',            'Taxas cooperadas',        'Ate 84 meses', 'from-emerald-700 to-emerald-600','SI', 50, true),
  ('Losango',   'https://www.losango.com.br',                                     'Consulte condicoes',      'Ate 72 meses', 'from-purple-700 to-purple-600',  'LO', 60, true)
ON CONFLICT (nome) DO UPDATE
SET
  url = excluded.url,
  taxa_texto = excluded.taxa_texto,
  prazo_texto = excluded.prazo_texto,
  cor_css = excluded.cor_css,
  icone_texto = excluded.icone_texto,
  ordem = excluded.ordem,
  ativo = excluded.ativo,
  updated_at = now();

-- -----------------------------
-- AUDITORIA DEPOIS
-- -----------------------------
-- select column_name, data_type, is_nullable
-- from information_schema.columns
-- where table_schema = 'public' and table_name = 'propostas'
--   and column_name like 'custom_%'
-- order by column_name;

-- select proposal_mode, count(*)
-- from public.propostas
-- group by proposal_mode
-- order by proposal_mode;

-- select *
-- from public.financiadoras
-- where ativo = true
-- order by ordem;