-- ============================================================================
-- Chat backend versioned in repository
-- Creates tables, RLS and RPCs used by the frontend chat module.
-- ============================================================================

create extension if not exists pgcrypto;

create table if not exists public.chat_conversations (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('direct', 'group')),
  title text null,
  direct_key text unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_participants (
  conversation_id uuid not null references public.chat_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz null,
  primary key (conversation_id, user_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.chat_conversations(id) on delete cascade,
  sender_user_id uuid not null references auth.users(id) on delete cascade,
  sender_nome text null,
  body text not null,
  kind text not null default 'text',
  reply_to_message_id bigint null references public.chat_messages(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists chat_participants_user_id_idx
  on public.chat_participants (user_id);

create index if not exists chat_messages_conversation_created_idx
  on public.chat_messages (conversation_id, created_at desc, id desc);

alter table public.chat_conversations enable row level security;
alter table public.chat_participants enable row level security;
alter table public.chat_messages enable row level security;

drop policy if exists "chat_conversations_select" on public.chat_conversations;
drop policy if exists "chat_participants_select" on public.chat_participants;
drop policy if exists "chat_messages_select" on public.chat_messages;

create policy "chat_conversations_select" on public.chat_conversations
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_participants cp
      where cp.conversation_id = public.chat_conversations.id
        and cp.user_id = auth.uid()
    )
  );

create policy "chat_participants_select" on public.chat_participants
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_participants cp
      where cp.conversation_id = public.chat_participants.conversation_id
        and cp.user_id = auth.uid()
    )
  );

create policy "chat_messages_select" on public.chat_messages
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_participants cp
      where cp.conversation_id = public.chat_messages.conversation_id
        and cp.user_id = auth.uid()
    )
  );

create or replace function public.chat_list_directory(
  p_search text default null,
  p_limit integer default 50
)
returns table (
  user_id uuid,
  email text,
  nome text,
  role text,
  franquia_id uuid,
  franquia_nome text,
  avatar_url text
)
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_role text := public.current_user_role();
  v_franquia_id uuid := public.current_franquia_id();
  v_gestor_user_id uuid := null;
  v_limit integer := least(greatest(coalesce(p_limit, 50), 1), 200);
  v_like text := null;
begin
  if not public.chat_can_use_current_user() then
    raise exception 'sem acesso ao chat'
      using errcode = 'P0001';
  end if;

  if nullif(trim(coalesce(p_search, '')), '') is not null then
    v_like := '%' || trim(p_search) || '%';
  end if;

  select cua.gestor_user_id
    into v_gestor_user_id
  from public.chat_user_access cua
  where cua.user_id = v_user_id;

  return query
  with users_base as (
    select
      u.id as user_id,
      lower(trim(u.email)) as email,
      coalesce(nullif(trim(p.nome), ''), split_part(coalesce(u.email, ''), '@', 1)) as nome,
      coalesce(u.raw_app_meta_data ->> 'role', 'vendedor') as role,
      coalesce(p.franquia_id, nullif(u.raw_app_meta_data ->> 'franquia_id', '')::uuid) as franquia_id,
      f.nome as franquia_nome,
      p.avatar_url,
      coalesce(p.ativo, false) as ativo,
      coalesce(cua.chat_enabled, false) as chat_enabled
    from auth.users u
    left join public.profiles p on p.id = u.id
    left join public.chat_user_access cua on cua.user_id = u.id
    left join public.franquias f on f.id = coalesce(p.franquia_id, nullif(u.raw_app_meta_data ->> 'franquia_id', '')::uuid)
    where u.id <> v_user_id
  )
  select
    ub.user_id,
    ub.email,
    ub.nome,
    ub.role,
    ub.franquia_id,
    ub.franquia_nome,
    ub.avatar_url
  from users_base ub
  where ub.ativo
    and ub.chat_enabled
    and (
      v_role = 'admin'
      or (v_role = 'gestor' and ub.franquia_id = v_franquia_id and ub.role in ('gestor', 'vendedor'))
      or (v_role = 'vendedor' and ub.user_id = v_gestor_user_id and ub.role = 'gestor')
    )
    and (
      v_like is null
      or ub.nome ilike v_like
      or ub.email ilike v_like
      or coalesce(ub.franquia_nome, '') ilike v_like
    )
  order by lower(ub.nome), lower(ub.email)
  limit v_limit;
end;
$$;

create or replace function public.chat_start_direct(
  p_other_user_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_conversation_id uuid;
  v_direct_key text;
begin
  if not public.chat_can_use_current_user() then
    raise exception 'sem acesso ao chat'
      using errcode = 'P0001';
  end if;

  if p_other_user_id is null or p_other_user_id = v_user_id then
    raise exception 'destinatario_invalido'
      using errcode = 'P0001';
  end if;

  if not exists (
    select 1
    from public.chat_list_directory(null, 200) directory
    where directory.user_id = p_other_user_id
  ) then
    raise exception 'sem acesso ao chat'
      using errcode = 'P0001';
  end if;

  v_direct_key := case
    when v_user_id::text < p_other_user_id::text then v_user_id::text || ':' || p_other_user_id::text
    else p_other_user_id::text || ':' || v_user_id::text
  end;

  insert into public.chat_conversations (kind, direct_key, created_by)
  values ('direct', v_direct_key, v_user_id)
  on conflict (direct_key) do update
    set updated_at = now()
  returning id into v_conversation_id;

  insert into public.chat_participants (conversation_id, user_id)
  values (v_conversation_id, v_user_id), (v_conversation_id, p_other_user_id)
  on conflict do nothing;

  return v_conversation_id;
end;
$$;

create or replace function public.chat_list_conversations(
  p_search text default null,
  p_limit integer default 50,
  p_offset integer default 0,
  p_include_archived boolean default false
)
returns table (
  conversation_id uuid,
  kind text,
  title text,
  participant_count integer,
  other_user_id uuid,
  other_email text,
  other_nome text,
  other_profile_nome text,
  other_avatar_url text,
  other_role text,
  other_franquia_nome text,
  last_message_preview text,
  last_message_at timestamptz,
  unread_count bigint,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 50), 1), 200);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_like text := null;
begin
  if not public.chat_can_use_current_user() then
    raise exception 'sem acesso ao chat'
      using errcode = 'P0001';
  end if;

  if nullif(trim(coalesce(p_search, '')), '') is not null then
    v_like := '%' || trim(p_search) || '%';
  end if;

  return query
  with my_conversations as (
    select c.id, c.kind, c.title, c.created_at, cp.last_read_at
    from public.chat_conversations c
    join public.chat_participants cp
      on cp.conversation_id = c.id
    where cp.user_id = v_user_id
  ),
  last_messages as (
    select
      m.conversation_id,
      left(m.body, 160) as body,
      m.created_at,
      row_number() over (partition by m.conversation_id order by m.created_at desc, m.id desc) as rn
    from public.chat_messages m
    join my_conversations mc on mc.id = m.conversation_id
  ),
  participant_counts as (
    select cp.conversation_id, count(*)::integer as participant_count
    from public.chat_participants cp
    join my_conversations mc on mc.id = cp.conversation_id
    group by cp.conversation_id
  ),
  other_participants as (
    select
      mc.id as conversation_id,
      op.user_id,
      op.email,
      op.nome,
      op.profile_nome,
      op.avatar_url,
      op.role,
      op.franquia_nome
    from my_conversations mc
    left join lateral (
      select
        u.id as user_id,
        lower(trim(u.email)) as email,
        coalesce(nullif(trim(p.nome), ''), split_part(coalesce(u.email, ''), '@', 1)) as nome,
        p.nome as profile_nome,
        p.avatar_url,
        coalesce(u.raw_app_meta_data ->> 'role', 'vendedor') as role,
        f.nome as franquia_nome
      from public.chat_participants cp2
      join auth.users u on u.id = cp2.user_id
      left join public.profiles p on p.id = u.id
      left join public.franquias f on f.id = coalesce(p.franquia_id, nullif(u.raw_app_meta_data ->> 'franquia_id', '')::uuid)
      where cp2.conversation_id = mc.id
        and cp2.user_id <> v_user_id
      order by lower(coalesce(p.nome, u.email))
      limit 1
    ) op on true
  )
  select
    mc.id as conversation_id,
    mc.kind,
    case when mc.kind = 'direct'
      then coalesce(op.nome, op.email, 'Conversa')
      else coalesce(mc.title, 'Grupo')
    end as title,
    coalesce(pc.participant_count, 0) as participant_count,
    op.user_id as other_user_id,
    op.email as other_email,
    op.nome as other_nome,
    op.profile_nome as other_profile_nome,
    op.avatar_url as other_avatar_url,
    op.role as other_role,
    op.franquia_nome as other_franquia_nome,
    coalesce(lm.body, '') as last_message_preview,
    lm.created_at as last_message_at,
    (
      select count(*)::bigint
      from public.chat_messages unread
      where unread.conversation_id = mc.id
        and unread.sender_user_id <> v_user_id
        and unread.created_at > coalesce(mc.last_read_at, '-infinity'::timestamptz)
    ) as unread_count,
    mc.created_at
  from my_conversations mc
  left join last_messages lm on lm.conversation_id = mc.id and lm.rn = 1
  left join participant_counts pc on pc.conversation_id = mc.id
  left join other_participants op on op.conversation_id = mc.id
  where (
    v_like is null
    or (mc.kind = 'direct' and (
      coalesce(op.nome, '') ilike v_like
      or coalesce(op.email, '') ilike v_like
      or coalesce(op.franquia_nome, '') ilike v_like
    ))
    or (mc.kind <> 'direct' and coalesce(mc.title, '') ilike v_like)
  )
  order by coalesce(lm.created_at, mc.created_at) desc, mc.created_at desc
  limit v_limit
  offset v_offset;
end;
$$;

create or replace function public.chat_list_messages(
  p_conversation_id uuid,
  p_limit integer default 200,
  p_before timestamptz default null
)
returns table (
  id bigint,
  conversation_id uuid,
  body text,
  kind text,
  created_at timestamptz,
  sender_user_id uuid,
  sender_nome text,
  is_me boolean
)
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 200), 1), 500);
begin
  if not public.chat_can_use_current_user() then
    raise exception 'sem acesso ao chat'
      using errcode = 'P0001';
  end if;

  if not exists (
    select 1
    from public.chat_participants cp
    where cp.conversation_id = p_conversation_id
      and cp.user_id = auth.uid()
  ) then
    raise exception 'sem acesso ao chat'
      using errcode = 'P0001';
  end if;

  return query
  with selected_rows as (
    select
      m.id,
      m.conversation_id,
      m.body,
      m.kind,
      m.created_at,
      m.sender_user_id,
      m.sender_nome,
      row_number() over (order by m.created_at desc, m.id desc) as rn
    from public.chat_messages m
    where m.conversation_id = p_conversation_id
      and (p_before is null or m.created_at < p_before)
    order by m.created_at desc, m.id desc
    limit v_limit
  )
  select
    sr.id,
    sr.conversation_id,
    sr.body,
    sr.kind,
    sr.created_at,
    sr.sender_user_id,
    coalesce(sr.sender_nome, sp.nome, split_part(coalesce(su.email, ''), '@', 1)) as sender_nome,
    sr.sender_user_id = auth.uid() as is_me
  from selected_rows sr
  left join public.profiles sp on sp.id = sr.sender_user_id
  left join auth.users su on su.id = sr.sender_user_id
  order by sr.created_at asc, sr.id asc;
end;
$$;

create or replace function public.chat_send_message(
  p_conversation_id uuid,
  p_body text,
  p_reply_to_message_id bigint default null,
  p_kind text default 'text'
)
returns bigint
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_message_id bigint;
  v_body text := trim(coalesce(p_body, ''));
  v_sender_nome text;
begin
  if not public.chat_can_use_current_user() then
    raise exception 'sem acesso ao chat'
      using errcode = 'P0001';
  end if;

  if v_body = '' then
    raise exception 'mensagem_vazia'
      using errcode = 'P0001';
  end if;

  if not exists (
    select 1
    from public.chat_participants cp
    where cp.conversation_id = p_conversation_id
      and cp.user_id = auth.uid()
  ) then
    raise exception 'sem acesso ao chat'
      using errcode = 'P0001';
  end if;

  select coalesce(nullif(trim(p.nome), ''), split_part(coalesce(u.email, ''), '@', 1))
    into v_sender_nome
  from auth.users u
  left join public.profiles p on p.id = u.id
  where u.id = auth.uid();

  insert into public.chat_messages (
    conversation_id,
    sender_user_id,
    sender_nome,
    body,
    kind,
    reply_to_message_id
  )
  values (
    p_conversation_id,
    auth.uid(),
    v_sender_nome,
    v_body,
    coalesce(nullif(trim(p_kind), ''), 'text'),
    p_reply_to_message_id
  )
  returning id into v_message_id;

  update public.chat_conversations
     set updated_at = now()
   where id = p_conversation_id;

  return v_message_id;
end;
$$;

create or replace function public.chat_mark_read(
  p_conversation_id uuid
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.chat_can_use_current_user() then
    raise exception 'sem acesso ao chat'
      using errcode = 'P0001';
  end if;

  update public.chat_participants
     set last_read_at = now()
   where conversation_id = p_conversation_id
     and user_id = auth.uid();

  if not found then
    raise exception 'sem acesso ao chat'
      using errcode = 'P0001';
  end if;
end;
$$;

revoke execute on function public.chat_list_directory(text, integer) from public, anon;
revoke execute on function public.chat_start_direct(uuid) from public, anon;
revoke execute on function public.chat_list_conversations(text, integer, integer, boolean) from public, anon;
revoke execute on function public.chat_list_messages(uuid, integer, timestamptz) from public, anon;
revoke execute on function public.chat_send_message(uuid, text, bigint, text) from public, anon;
revoke execute on function public.chat_mark_read(uuid) from public, anon;

grant execute on function public.chat_list_directory(text, integer) to authenticated;
grant execute on function public.chat_start_direct(uuid) to authenticated;
grant execute on function public.chat_list_conversations(text, integer, integer, boolean) to authenticated;
grant execute on function public.chat_list_messages(uuid, integer, timestamptz) to authenticated;
grant execute on function public.chat_send_message(uuid, text, bigint, text) to authenticated;
grant execute on function public.chat_mark_read(uuid) to authenticated;
